### ISSUE TITLE
Enhancement request - Splitboard specific requirements

### ISSUE THREAD

**Issue by splitn2** [mikemag/MonkeyCAM#11]
Touring bracket and heel riser insert pattern - in inches.....

Splitboard insert pattern for mounting Voile pucks - this is not 40x40mm its actually in inches!!!

The cut down the middle!!!!! So the board is really 2 mirrored halves of course, ideally the board is made with one whole core that is made 6mm wider in the middle to allow for bandsaw to rip through and for the 2 inside edges. The core should have at least 3 alignment dowels to the base end/middle/end as it is critical to a splitboard to helping keep the inside edges dead straight and parallel while laying up and pressing.

Bases are cut with the allowance for the inside edge 2mm also (I use 2x2mm edge profile with 1.4mm step)

tip/tail spacers ideally be modded to include some wrap into the inside sidewall

inside edge sidewall trench for hard inlay timber or plastic same as normal outside sidewall - just add a 14mm stringer cut down the middle to allow for 2 x 6mm sidewalls and a 2mm final gap for the bandsaw rip

so there you go Mike I work in inches and metric too!!! haha I totally get you about this, even my 14 year old son like to work in inches too.

I'll forward the insert pattern dimensions to you ok. Or try attach to this github

cheers
Rich

**Comment by splitn2** [comment]
@toddrednz if you're up to the task mate this would be an awesome area for you to contribute into MonkeyCAM development. I'm getting closer to a production cnc system and in the ideal scenario having Splitboard functionality in MonkeyCAM would be amazing. @mikemag has done some work on this in the past versions of MonkeyCAM but its quite a task to bring this into the current V4 stream so perhaps if its ok and you could reach out to Mike and see if its within your ability and not making Mikes life or yours too hard. If you can crack this and get it running sweet then there is a SPLITN2 custom board for you ok mate. Only, only, if its not a hassle for either of you, especially Mike I know he's a busy man and Todd your phd studies need to be priority too eh!

**Comment by toddrednz** [comment]
Yeah, I'm keen to have a crack! It won't happen overnight, but steady and slow, that's my style! haha. @mikemag I'd be keen to see how you've approached implementing aspects of this in the past, and then I can get my head around how to take this forward?

**Comment by splitn2** [comment]
@toddrednz the beauty of MonkeyCAM is that it helps speed up the end to end process from design to materials cutting on the cnc, it adds a great deal of built in snowboard construction process and intelligence to the CAM gcode generation based on knowledge of how in snowboard production a core is profiled and drilled etc and the shapes of the plastic base and tip/tail spacers , saving huge amounts of CAM time. MonkeyCAM makes all these parts fit perfectly. My suggestion is when you guys have a chance to do a bit of knowledge transfer to Todd then I will help Todd to take this to the next stage of development for splitboards. There are some quite neat things we can do here to make splitboard construction better more accurate and faster and less risky with core mis-alignment risk eliminated. Maybe as Todds level of understanding increases we can look at SnoCAD integration too, slowly is fine too, my clock ticks pretty slow!

**Comment by mikemag** [comment]
Checkout the design overview in the wiki on this site, specifically this https://github.com/mikemag/MonkeyCAM/wiki/Building-Shapes on building shapes and this https://github.com/mikemag/MonkeyCAM/wiki/Coordinates-and-units on coordinates.

Suggestion based on the current v4 implementation, and based on what I did in v2 and v3 for splitboards:

1. Split the overall shape in half, either with a boolean op or by brute force (filter the overall shape path into two separate paths based on what's above and below y=0). Call these two pieces the overall shape halves (OSH). 
1. Hold onto both OSH for later. They can be offset inward by 2mm each and used to form the paths to cut the base material. 
1. Shift the two OSH in Y by a configurable amount, to leave a kerf for cutting the final board in half when layup is completed. If we want a 2mm kerf then it would be -1mm in Y for the lower half and +1mm in Y for the upper half.
1. Join the two OSH back together to form a new Overall Shape path. Obviously keep the halves in order, and ensure that the start/end of the new path is at (0,0).
1. For the core:
  1. The majority of it proceeds exactly the same as usual. The core path can be formed as normal, nose and tail spacers, everything. 
  1. `generateCoreEdgeGroove()`: we'll need a groove down the center of the board, for the inner edges. This is likely most easily formed by a brute-force box around the Y axis the length of the board. Don't let the cutter go past the normal bounds of the outer edge trench on the ends. In v3 this took three passes with a 1/4" cutter, and the passes were added onto the end of the normal passes.
  1. `generateEdgeTrench()`: we'll need a trench down the center of the board for the sidewall material, and optionally for a different kind of wood stringer, just like the edge trenches. Again, most likely easy with a brute-force box around the Y axis. Configurable width of course... some people don't care for an extra wood stringer on their inner edges, and sidewall material can be different widths. As above, add the new trench passes in after the normal edge trenches. Don't go much beyond the ends of the board, if at all... the trimming for the nose/tail spacers will remove a lot of the trench anyway, and the less wood you remove the more structural the core blank remains.
1. Inserts: this is the easy part.
  1. Continue to have insert packs specified in the current scheme, but of course they have an odd spacing as shown in Rich's pic in this comment: https://github.com/mikemag/MonkeyCAM/issues/11#issuecomment-56737890. Consider an explicit "splitboard inserts" option, but still let them configure the count of inserts nose and tail as usual. 
  1. Add the other inserts in the required places. There is something to be thought about with placement of the toe pivot... there's probably a good place for it relative to the center of the effective edge. Provide an option to use EE center vs. overall center, and provide an extra setback option specifically for this set of inserts, so people can control where the toe pivot goes.

That, as I recall, is all there is too it. This is a fun addition to MonkeyCAM that people will love.

For reference, I'm attaching a bunch of pictures of a splitboard core I cut with MonkeyCAM v3 years ago.
![20150906_183316_001](https://cloud.githubusercontent.com/assets/3166600/9708054/1d30ddc8-54cb-11e5-8d31-5392a05845b8.jpg)
![20150906_183258](https://cloud.githubusercontent.com/assets/3166600/9708053/1d308fe4-54cb-11e5-9962-4d4e185c7b3d.jpg)
![20150906_183253](https://cloud.githubusercontent.com/assets/3166600/9708050/1d2e20d8-54cb-11e5-8325-8eda68f2f523.jpg)
![20150906_183241](https://cloud.githubusercontent.com/assets/3166600/9708052/1d302220-54cb-11e5-895e-a66378ed9955.jpg)
![20150906_183231](https://cloud.githubusercontent.com/assets/3166600/9708055/1d316310-54cb-11e5-915a-2374d0941a35.jpg)
![20150906_183157](https://cloud.githubusercontent.com/assets/3166600/9708051/1d2f7f14-54cb-11e5-9cad-febaf026fda1.jpg)

**Comment by splitn2** [comment]
@toddrednz BUMP !!!! haha you know its 2016 now and we are counting down to winter. I'll bribe you with a SPLITN2 splitboard if you can nail this with quality code!!!!!

**Comment by mikemag** [comment]
I'm in the middle of doing this, I should have marked it as such!

**Comment by mikemag** [comment]
Made a bunch of progress on this today, here are some current results: https://www.monkeycam.org/results/5637369860456448
Direct link to the overview output: https://storage.googleapis.com/monkeycam-results/5637369860456448/Sample-splitboard-20180305-220512-overview.html

**This is not active on monkeycam.org at this time. I cheated to get those links up there :)**

I need to fix up a minor mistake in the way the shapes are spread apart for the center gap, then I'll be ready to check this in. 

New machine parameters:
- "splitboard center trench width": 0.5,                                                  
- "splitboard center gap": 0.100,                                                         
 
New board parameter:
- "splitboard": true,                                                                     

I've got the Voile insert pattern in a sample binding def file, taken from http://www.voile.com/voile_splitboard_hole_pattern_specs.pdf, retrieved today.

Once I get this up there properly and people get a chance to play with it we can adjust as necessary.

**Comment by splitn2** [comment]
OMG!!!!! this is nuts !!!! I will have a play, thanks so much Mike this is legendary!!!!

**Comment by sou-l** [comment]
agreed. this is rad. Just need a cnc now

**Comment by mikemag** [comment]
I've committed the splitboard support. I'll leave this issue open until I update MonkeyCAM.org, probably later today or tomorrow.

**Comment by mikemag** [comment]
Oh, I need to update the docs on how inserts are specified to cover what I did there.
