### ISSUE TITLE
Could a "simple" background process make it almost realtime as we fill out a form?

### ISSUE THREAD

**Issue by splitn2** [mikemag/MonkeyCAM#19]
Simple, well definitely not for me but maybe for a whizz programmer its a go-er. So what I mean is we have a "GUI" that is the current brilliant SVG html output, which is updated almost in real time as the MonkeyCAM computes svg and the gcode based on the entries entered into a simple form?

The form updates the json file automatically as every change is committed to the form with a tab or enter keystroke after each field is tweaked, then the html file displayed with the svg is automatically updated and refreshed...... or there is a "commit" button at the bottom of the table form.

Now just to be clear Mike, I do not expect you to do this , its just a suggestion and I know I've been quite prolific with my input!!!! So please forgive me mate if this is just one step too far! What you have created here is simply mind boggling.

cheers
Rich

**Comment by mikemag** [comment]
This will be covered with integration to SnoCAD-X.
