### ISSUE TITLE
problem executing on MAC???? see issue details for how to work around this....

### ISSUE THREAD

**Issue by splitn2** [mikemag/MonkeyCAM#22]
Rileys-iMac:MonkeyCAM-4.0.3 new$ ./bin/MonkeyCam --board ./example/board-def.json --machine ./example/machine-tool-def.json
MonkeyCAM v4.0.3, Copyright (C) 2013-2014 Michael M. Magruder
This is free software; see the source for license information. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Using board './example/board-def.json', machine './example/machine-tool-def.json'
Building board shapes...
Generating G-code programs to './'...
Sample-snowboard-top-profile.nc
Assertion failed: (o.is_open()), function write, file /Users/Mike/dev/MonkeyCAM/core/gcode-writer.cpp, line 412.
Abort trap: 6
Rileys-iMac:MonkeyCAM-4.0.3 new$

running OSX 10.9.5

I mounted the dwg file and its all there, and its executing but bombing out, i tried various relative and absolute pathnames working out of the MonkeyCAM root or in MonkeyCAM/bin directories and it made no difference. Need the guru input now Mike!!!!

**Comment by mikemag** [comment]
The issue here is that the DMG file is read-only, but the command above tried to get MonkeyCAM to write into the DMG. You can use the --outdir option to specify a different destination if necessary.
