### ISSUE TITLE
monkeyCAM

### ISSUE THREAD

**Issue by robpato** [mikemag/MonkeyCAM#28]
hello, 
i cant seem to start monkeyCAM on my laptop. once i try open it i get a small screen flash up for a second then it drops out. not sure what to do?

**Comment by splitn2** [comment]
hi @robpato I can show you how to use MonkeyCAM, I'll be running an online meeting to demo it, will include you in the invite ok. cheers, Richard

**Comment by robpato** [comment]
Ok that would be good thanks
