### ISSUE TITLE
Mac Help

### ISSUE THREAD

**Issue by rideoutjoey** [mikemag/MonkeyCAM#29]
I'm sure it's me but I cant figure out for the life of me how to get this downloaded on my mac and running.

**Comment by splitn2** [comment]
hi @rideoutjoey I can help no problems do you want to do a Skype session and I can show you exactly how I use MonkeyCAM? cheers, Rich

**Comment by mikemag** [comment]
Start here: https://github.com/mikemag/MonkeyCAM/releases/tag/v4.0.3. Download the .dmg file (bottom of the page) and follow the instructions under Mac on that page. Let us know if you run into any trouble, and include a copy of the commands you tried and their output.
