### ISSUE TITLE
MonkeyCam Error

### ISSUE THREAD

**Issue by antoxasam** [mikemag/MonkeyCAM#48]
Something happened to your web app MonkeyCam. An error occurs after clicking the button "Run MonkeyCam". Error "The server returned an error: TypeError: Failed to fetch". Look, please, what happened? Your application is very useful and I would like to use it. Thank you:)

**Comment by mikemag** [comment]
This appears to be working when I try it. There may have been a transient failure in one of Google's backend services. Let me know if it's still happening for you.
